### ISSUE TITLE
Návrh implementácie

### ISSUE THREAD

**Issue by klaaudii** [TIS2021-FMFI/sklad#16]
- [x] UML component diagram
- [x] UML class diagram
- [x] UML state/UML sequence diagram
- [x] architektúra
- [ ] rozdelenie na moduly a interfejsy
- [x] technológie

**Comment by jacque157** [comment]
Návrh UML class diagramu:
https://drive.google.com/file/d/1LOJ3L6eMZoLlwEtzR4IJQIm_oqU-cAiv/view?usp=sharing

**Comment by jacque157** [comment]
Stavový diagram:
https://drive.google.com/file/d/1pBwFhCnE4nOWU6ZCC-21dvYc0YYn0hnU/view?usp=sharing

**Comment by jacque157** [comment]
Diagram komponentov:
https://drive.google.com/file/d/1mD3cLhLDberv10B03mMMHdi0_69JRijk/view?usp=sharing
