### ISSUE TITLE
Návrh

### ISSUE THREAD

**Issue by klaaudii** [TIS2021-FMFI/sklad#21]

**Comment by klaaudii** [comment]
https://docs.google.com/document/d/1vUONwFqmN9m-3fkhzORHHNRWKXKwGflxa3UOolPX0VY/edit

**Comment by valent32** [comment]
Návrh na ktorom pracujeme.
https://docs.google.com/document/d/1vUONwFqmN9m-3fkhzORHHNRWKXKwGflxa3UOolPX0VY/edit

**Comment by pavelpetrovic** [comment]
![stavovy](https://user-images.githubusercontent.com/13798920/142040675-1b604eb9-1a5d-487b-aeeb-96938a063d0b.png)
